# Alias definitions.
alias addcomputer.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/addcomputer.py'
alias atexec.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/atexec.py'
alias dcomexec.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/dcomexec.py'
alias dpapi.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/dpapi.py'
alias esentutl.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/esentutl.py'
alias findDelegation.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/findDelegation.py'
alias GetADUsers.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/GetADUsers.py'
alias getArch.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/getArch.py'
alias GetNPUsers.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/GetNPUsers.py'
alias getPac.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/getPac.py'
alias getST.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/getST.py'
alias getTGT.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/getTGT.py'
alias GetUserSPNs.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/GetUserSPNs.py'
alias goldenPac.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/goldenPac.py'
alias ifmap.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/ifmap.py'
alias karmaSMB.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/karmaSMB.py'
alias kintercept.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/kintercept.py'
alias lookupsid.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/lookupsid.py'
alias mimikatz.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/mimikatz.py'
alias mqtt_check.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/mqtt_check.py'
alias mssqlclient.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/mssqlclient.py'
alias mssqlinstance.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/mssqlinstance.py'
alias netview.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/netview.py'
alias nmapAnswerMachine.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/nmapAnswerMachine.py'
alias ntfs-read.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/ntfs-read.py'
alias ntlmrelayx.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/ntlmrelayx.py'
alias opdump.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/opdump.py'
alias ping6.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/ping6.py'
alias ping.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/ping.py'
alias psexec.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/psexec.py'
alias raiseChild.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/raiseChild.py'
alias rdp_check.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/rdp_check.py'
alias registry-read.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/registry-read.py'
alias reg.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/reg.py'
alias rpcdump.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/rpcdump.py'
alias sambaPipe.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/sambaPipe.py'
alias samrdump.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/samrdump.py'
alias secretsdump.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/secretsdump.py'
alias services.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/services.py'
alias smbclient.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/smbclient.py'
alias smbexec.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/smbexec.py'
alias smbrelayx.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/smbrelayx.py'
alias smbserver.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/smbserver.py'
alias sniffer.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/sniffer.py'
alias sniff.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/sniff.py'
alias split.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/split.py'
alias ticketConverter.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/ticketConverter.py'
alias ticketer.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/ticketer.py'
alias wmiexec.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/wmiexec.py'
alias wmipersist.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/wmipersist.py'
alias wmiquery.py='/usr/bin/python3 /usr/share/doc/python3-impacket/examples/wmiquery.py'
# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -lhaF'
alias '..'='cd ..'
#git
alias gs="git status"
alias gp="git pull"
alias gl="git log"
alias gd="git diff -w"
alias gdw="git diff"
alias gds="git diff --staged"
alias ga="git add"
alias gb="git branch"
alias sudo="sudo "
alias aptsn="apt-cache search --names-only"
alias s="screen"
alias aptli="apt list --installed"
alias sb="sudo bash"
alias vsl="virsh list --all"
alias lt='ls -lhaFt --reverse'
alias topmem='top -1 -o %MEM -e m -c'
alias htopmem='htop -s PERCENT_MEM -d 10'
#docker
alias dols='docker ps'
alias doim='docker image ls'
alias doshow='docker container inspect'
alias dostats='docker container stats'
alias dostart='docker container start -i'
alias grep='grep --color'
alias zenc='7z a -p -mhe=on'
alias sgptshell='sgpt --repl temp --shell'

pg() {
	if [ -z "$1" ]; then
		echo "Usage: pg <process name>"
	else
		/usr/bin/pgrep -alf "$1" | /usr/bin/grep --color=auto "$1"
	fi
}

doexec() {
	[ -z "$2" ] && docker container exec -it -u root $1 /bin/bash || docker container exec -it -u $1 $2 /bin/bash
}

dorun() {
	docker run -it -u root $1 /bin/bash
}


lsten() {
	if [ -z "$1" ]; then
		/usr/bin/sudo /usr/bin/lsof -nP -sTCP:LISTEN -iTCP; /usr/bin/sudo /usr/bin/lsof -nP -iUDP
	else
		/usr/bin/sudo /usr/bin/lsof -nP -sTCP:LISTEN -iTCP:$1; /usr/bin/sudo /usr/bin/lsof -nP -iUDP:$1 
	fi
}

f() {
	set -x
    /usr/bin/find . \( -path "/mnt" -o -path "/media" -o -path "/dev" \) -prune -o -iname "$@"
	set +x
}
